import { useState, useRef, useEffect } from 'react';
import Head from 'next/head';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronUp } from '@fortawesome/free-solid-svg-icons';
import Navbar from '../components/Navbar';
import Home from '../components/Home';
import About from '../components/About';
import Education from '../components/Education';
import Experience from '../components/Experience';
import Portfolio from '../components/Portfolio';
import Contact from '../components/Contact';
import Footer from '../components/Footer';

export default function Index() {
  const containerRef = useRef(null);
  const [solidBg, setSolidBg] = useState(false);
  const [active, setActive] = useState(false);

  const callbackFunction = entries => {
    const [entry] = entries;
    setActive(entry.isIntersecting);
  };

  const options = {
    root: null,
    rootMargin: '20px',
    threshold: 0.1,
  };

  useEffect(
    () => {
      const observer = new IntersectionObserver(callbackFunction, options);
      if (containerRef.current) observer.observe(containerRef.current);

      return () => {
        if (containerRef.current) observer.unobserve(containerRef.current);
      };
    },
    containerRef,
    options
  );

  return (
    <>
      {/* <div className={'container'}> */}
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />

        <meta charSet='utf-8' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, maximum-scale=1'
        />
        <title>Duane McDonald | Software Developer</title>
        <meta
          name='description'
          content='Duane McDonald | Software Engineer | Small Business Solutions | Web Developer'
        />
        <meta name='author' content='Duane McDonald' />
      </Head>

      <Navbar />
      <div id='#top' />
      <Home />
      <About />
      <Education />
      <Experience />
      <Portfolio />
      <Contact />
      <Footer />

      {/*         
        // <script src='js/modernizr-latest.js'></script>
        // <script src='js/jquery-1.8.2.min.js' type='text/javascript'></script>
        // <script src='js/bootstrap.min.js' type='text/javascript'></script>
        // <script src='js/jquery.isotope.min.js' type='text/javascript'></script>
        // <script
        //   src='js/fancybox/jquery.fancybox.pack.js'
        //   type='text/javascript'></script>
        // <script src='js/jquery.nav.js' type='text/javascript'></script>
        // <script src='js/jquery.cslider.js' type='text/javascript'></script>
        // <script src='js/jquery.diagram.js'></script>
        // <script src='contact/jqBootstrapValidation.js'></script>
        // <script src='contact/contact_me.js'></script>

        // <script src='js/custom.js' type='text/javascript'></script>
      // <script src='js/owl-carousel/owl.carousel.js'></script> */}
      <a href='#top' className={'topHome'}>
        <FontAwesomeIcon size='3x' icon={faChevronUp} />
      </a>
      {/* </div> */}
    </>
  );
}
